module.exports = {
  en: {
    translation: {
      POSITIVE_SOUND: `<audio src='soundbank://soundlibrary/ui/gameshow/amzn_ui_sfx_gameshow_positive_response_02'/>`,
      GREETING_SPEECHCON: `<say-as interpret-as="interjection">Hurrey</say-as>`,
      DOUBT_SPEECHCON: `<say-as interpret-as="interjection">hmm</say-as>`,
      WELCOME_MSG: `Hello mate, Welcome to HCL Hackathon Store. `,
      CATEGORY_MSG: `Today we have {{records}} categories for you to shop for: `,
      CATEGORY_NAME_MSG: `{{counter}}. {{categoryName}}, `,
      PRODUCT_MSG: `We have {{records}} products in {{categoryName}} category: `,
      PRODUCT_NAME_MSG: `{{counter}}. {{productName}}, `,
      PRODUCT_DETAIL_MSG: `You have choosen {{description}} Which has value of {{price}} USD. `,
      ADD_TO_CART_MSG: `Would you like to add {{quantity}} {{productName}} to your cart? `,
      PRODUCT_ADDED_TO_CART_MSG: `Your product successfully added to your cart. Cart total is {{price}} USD. $t(POSITIVE_SOUND) $t(GREETING_SPEECHCON) you got an offer: {{offer}}. Would you like to place the order? `,
      ORDER_PLACE_MSG: `Thankyou for placing the order. Your order id is {{orderId}} of amount {{piAmount}} USD. Your order is expected to be shipped soon. Further communication will be emailed. For queries visit HCL Hackathon Store. `,
      WELCOME_BACK_MSG: "Welcome back {{name}}! ",
      REJECTED_MSG: "Okay! No Problem. Thankyou. ",
      GREET_MSG: "$t(POSITIVE_SOUND) $t(GREETING_SPEECHCON) {{name}}. ",
      HELP_MSG:
        "I can place an order for you from HCL Hackathon Store, if you tell me the Product Details. I can also tell you the categories, products we have. Or allow you to add product to your cart. Finally I can Place the order for you. Would you like to try? ",
      REPROMPT_MSG: `If you're not sure what to do next try asking for help. If you want to leave just say stop. What would you like to do next? `,
      GOODBYE_MSG: [
        "Goodbye {{name}}! ",
        "So long {{name}}! ",
        "See you later {{name}}! ",
        "Cheers {{name}}! ",
      ],
      THANKYOU_MSG : `Thankyou! Stay Home Stay Safe. `,
      REFLECTOR_MSG: "You just triggered {{intent}}",
      FALLBACK_MSG: `Sorry, I don't know about that. Please try again.`,
      ERROR_MSG: "Sorry, there was an error. Please try again.",
      NO_TIMEZONE_MSG: `I can't determine your timezone. Please check your device settings and make sure a timezone was selected. After that please reopen the skill and try again!`,
      UNSUPPORTED_DEVICE_MSG: `This device doesn't support this operation. `,
      CANCEL_MSG: `Ok. Let's cancel that. `,
      API_ERROR_MSG: `I'm sorry, I'm having trouble accessing the external A.P.I., Please try again later. `,
      CONJUNCTION_MSG: " and ",
      TURNING_YO_MSG: " turning {{count}}",
    },
  },
};
